export type StorySceneKind = "main" | "branch" | "ending";

export interface StoryPanel {
  shot: string;
  imageDirection: string;
  narration?: string;
  dialogue?: string;
  interaction?: string;
}

export interface StoryChoice {
  label: string;
  consequence: string;
  moralTag: string;
}

export interface StoryScene {
  id: string;
  act: string;
  order: string;
  kind: StorySceneKind;
  title: string;
  subtitle: string;
  location: string;
  image: string;
  assetSlug: string;
  mood: string;
  mechanic: string;
  gameplay: string;
  description: string;
  panels: StoryPanel[];
  objectives: string[];
  choices?: StoryChoice[];
  artPrompt: string;
}

export const STORY_ACTS = [
  { id: "all", label: "全剧本" },
  { id: "第一幕", label: "第一幕" },
  { id: "第二幕", label: "第二幕" },
  { id: "第三幕", label: "第三幕" },
  { id: "第四幕", label: "第四幕" },
  { id: "最终章", label: "最终章" },
] as const;

const cinematicStyle =
  "Use case: illustration-story. Asset type: cinematic comic game scene panel. Original psychological horror IP, painterly 2D game illustration, wide 16:9, no text, no watermark, no recognizable external franchise references.";

export const STORY_SCENES: StoryScene[] = [
  {
    id: "scene-01-title-prologue",
    act: "第一幕",
    order: "01",
    kind: "main",
    title: "标题序幕",
    subtitle: "雾先等你开口",
    location: "灰洄镇外缘街道",
    image: "/assets/scenes/scene-tidal-street.png",
    assetSlug: "comic-scene-01-title-prologue",
    mood: "麻木、压抑、迟来的审判",
    mechanic: "封面交互、呼吸声、手电显影",
    gameplay: "玩家用鼠标扫动封面雾层，逐步显影标题、主角剪影和第一句旁白。",
    description:
      "全黑屏幕先给玩家听觉入口：呼吸、海浪、远处金属撞击。手电光划过时，灰洄镇像一张被水泡开的旧照片缓慢显形，沈迴站在折叠街道中央，既像归来者，也像被召回的证人。",
    panels: [
      {
        shot: "全黑开场",
        imageDirection: "只有一束晃动的暖色手电光切开浓雾，画面边缘是潮湿颗粒和胶片噪声。",
        narration: "雾不是天气，它是还没有说出口的记忆。",
        dialogue: "沈迴：他们说雾会散。但这里的雾只是在等。",
        interaction: "拖动光锥查看街面符号，停留三秒后标题显影。",
      },
      {
        shot: "俯视街道",
        imageDirection: "折叠向下的港镇街道、倾斜路灯、远处疗养院轮廓，主角背对镜头。",
        narration: "玩家第一次看到核心视觉：雾、手电、港镇、孤身归来的人。",
      },
    ],
    objectives: ["显影标题", "确认主角位置", "进入归潮街口"],
    artPrompt: `${cinematicStyle} Scene: a lone exhausted Chinese emergency doctor in a dark coat stands in a folded foggy harbor town street at night, holding an old flashlight into dense remembered fog, leaning street lamps, distant abandoned clinic silhouette, oppressive quiet mood, charcoal gray, oxidized green, muted amber flashlight.`,
  },
  {
    id: "scene-02-tidal-street-search",
    act: "第一幕",
    order: "02",
    kind: "main",
    title: "归潮街口 - 第一次探索",
    subtitle: "急救记录单在水洼里发冷",
    location: "归潮街口",
    image: "/assets/scenes/scene-tidal-street.png",
    assetSlug: "comic-scene-02-tidal-street-search",
    mood: "否认、试探、控制感薄弱",
    mechanic: "移动、手电宽窄切换、第一件证物",
    gameplay: "WASD 移动，F 切换宽光和聚焦。玩家必须用不同光锥发现急救记录单、婚戒和墙面涂字。",
    description:
      "街道不是现实空间，而是沈迴记忆的第一层外壳。路灯倾斜，店招褪色，地面缝隙向上吐雾。第一件证物不是跳出来的目标，而是被压在急救车旁水洼里的纸，要求玩家主动低头照亮。",
    panels: [
      {
        shot: "建立镜头",
        imageDirection: "破败港口街道，湿石板反光，旧急救车半陷在雾中。",
        narration: "玩家学会看见，也学会不敢看太久。",
        interaction: "聚焦手电扫过急救车轮胎，证物边缘反光。",
      },
      {
        shot: "证物特写",
        imageDirection: "溅血急救记录单、日期、沈迴签名，纸面被雨水泡皱。",
        dialogue: "沈迴：我尽力了。",
      },
    ],
    objectives: ["学习手电模式", "拾取急救记录单", "避开第一名游荡者"],
    artPrompt: `${cinematicStyle} Scene: foggy abandoned harbor street, old ambulance beside a puddle, a blood-stained emergency record reflected in water, flashlight beam from first-person angle, wet asphalt, leaning signs, tense psychological horror, no readable text.`,
  },
  {
    id: "scene-03-first-wanderer",
    act: "第一幕",
    order: "03",
    kind: "main",
    title: "第一次遭遇 - 游荡者",
    subtitle: "看见却转身的人",
    location: "归潮街口巷道",
    image: "/assets/scenes/scene-tidal-street.png",
    assetSlug: "comic-scene-03-first-wanderer",
    mood: "恐惧、否认、身体先于理智逃跑",
    mechanic: "追逐、视线遮挡、噪音暴露",
    gameplay: "游荡者会对强光和脚步作出反应。玩家必须绕过巷道，在冲刺噪音和距离之间作取舍。",
    description:
      "游荡者不是传统怪物登场，而是一段社会性沉默的形状。它在雾里重复走同一段路，直到玩家的手电照到它扭曲的肩线，它才像被提醒一样转身。",
    panels: [
      {
        shot: "分割画面",
        imageDirection: "左侧是雾中佝偻轮廓，右侧是沈迴发抖的手和手电。",
        narration: "它不急着杀你，它只是把你逼回你转身离开的那一刻。",
      },
      {
        shot: "巷内喘息",
        imageDirection: "主角背靠潮湿砖墙，手捂口鼻，雾影从巷口拖过。",
        dialogue: "沈迴：不是怪物，只是雾。雾会记得，对吧？",
        interaction: "保持静止降低噪音，让怪物离开搜索范围。",
      },
    ],
    objectives: ["完成第一次逃脱", "理解噪音条", "进入废弃公寓"],
    artPrompt: `${cinematicStyle} Scene: a twisted humanoid wanderer emerging from dense street fog, split-panel composition with trembling flashlight hand, wet alley walls, anxious motion blur, muted rust and green-gray palette, original monster silhouette.`,
  },
  {
    id: "scene-04-abandoned-apartment-radio",
    act: "第一幕",
    order: "04",
    kind: "main",
    title: "废弃公寓 - 收音机与记忆",
    subtitle: "墙纸下面在争吵",
    location: "废弃公寓",
    image: "/assets/scenes/scene-abandoned-apartment.png",
    assetSlug: "comic-scene-04-abandoned-apartment-radio",
    mood: "烦躁、防御、强制回忆",
    mechanic: "声源定位、收音机杂讯、墙内对白",
    gameplay: "玩家通过左右声道定位四台收音机。关错顺序会让走廊重新排列，关对顺序会打开电梯。",
    description:
      "公寓像一台坏掉的录音机，每扇门后都是同一间客厅。收音机播放的不是新闻，而是事故前后被剪碎的呼救、争吵与签字声。沈迴越想关掉它，噪音越会把怪物引近。",
    panels: [
      {
        shot: "室内长镜头",
        imageDirection: "破旧公寓走廊，信箱、寻人启事、剥落墙纸，远处一台老收音机发绿光。",
        narration: "声音不是背景，它是地图。",
        interaction: "跟随杂讯强弱找到收音机。",
      },
      {
        shot: "照片证物",
        imageDirection: "黑白抢救现场照片落在地上，三个人影被水和火烧痕遮住。",
        dialogue: "沈迴：为什么只救了一个？",
      },
    ],
    objectives: ["定位收音机", "拾取抢救现场照片", "启动电梯下沉"],
    artPrompt: `${cinematicStyle} Scene: abandoned apartment corridor with old radios glowing through peeling wallpaper, missing-person posters, wet floor reflections, a black-and-white rescue photo on the floor, claustrophobic cinematic framing.`,
  },
  {
    id: "scene-05-lin-chen-apparition",
    act: "第一幕",
    order: "05",
    kind: "main",
    title: "第一次遇见林晨的幻象",
    subtitle: "她没有说话，因为你已经知道",
    location: "公寓深处走廊",
    image: "/assets/characters/hallucination-shadow.png",
    assetSlug: "comic-scene-05-lin-chen-apparition",
    mood: "愧疚、惊惧、无声审判",
    mechanic: "幻象显影、墙面提示、理智波动",
    gameplay: "玩家靠近林晨幻象时屏幕声音被抽空，只剩心跳。转身查看墙面文字后才能继续前进。",
    description:
      "林晨第一次出现时不承担解释功能，她像沈迴不愿看见的证据。她背对玩家站在走廊尽头，手电光穿过她的身体；她转身后只指向沈迴背后的墙。",
    panels: [
      {
        shot: "静止远景",
        imageDirection: "半透明护士制服身影站在走廊尽头，周围雾被她的轮廓切开。",
        narration: "有些人不需要开口，因为你已经替她说完了所有控诉。",
      },
      {
        shot: "墙字特写",
        imageDirection: "潮湿墙面上用血水写着：他们还在等你。字迹模糊，不做清晰可读文本。",
        dialogue: "沈迴：我知道。我一直知道。",
      },
    ],
    objectives: ["跟随幻象", "读取墙面讯号", "承受第一次理智下降"],
    artPrompt: `${cinematicStyle} Scene: translucent nurse apparition in a ruined apartment corridor, flashlight beam passes through her body, wet walls, silent heartbeat atmosphere, restrained ghostly beauty, psychological horror without gore.`,
  },
  {
    id: "scene-06-first-descent",
    act: "第一幕",
    order: "06",
    kind: "main",
    title: "第一幕结束 - 下沉",
    subtitle: "不是为了逃，而是为了记起",
    location: "公寓楼顶仪式印记",
    image: "/assets/ui/recall-sigil.png",
    assetSlug: "comic-scene-06-first-descent",
    mood: "承认、仍然防御、进入讨价还价",
    mechanic: "仪式印记、章节过场、垂直折叠",
    gameplay: "玩家站入召回印记后，收集到的证物会按顺序闪回。确认后地图折叠，进入下一层。",
    description:
      "公寓楼顶没有出口，只有发光印记。下沉不是失败，而是进入更深的记忆层。建筑、街道和雾像纸张一样向下折叠，玩家第一次理解这是一个章节式循环。",
    panels: [
      {
        shot: "俯视楼顶",
        imageDirection: "主角站在金色召回印记上，脚下街道和楼梯向深处折叠。",
        narration: "雾不会放过你，但它也没有直接吞掉你。",
        dialogue: "沈迴：不是为了逃，是为了记起。",
      },
      {
        shot: "过场坠落",
        imageDirection: "公寓门变成白布覆盖的医院走廊，心电声从黑暗里响起。",
      },
    ],
    objectives: ["完成第一幕仪式", "保存证物", "进入铁锈医院"],
    artPrompt: `${cinematicStyle} Scene: glowing occult recall sigil on an apartment rooftop, foggy town architecture folding downward like paper, lone survivor with flashlight, surreal descent, gold light against green-gray fog.`,
  },
  {
    id: "scene-07-rust-hospital-entry",
    act: "第二幕",
    order: "07",
    kind: "main",
    title: "铁锈医院 - 聆听者的审判",
    subtitle: "地下停尸房箭头指向事故核心",
    location: "铁锈医院",
    image: "/assets/scenes/scene-rust-hospital.png",
    assetSlug: "comic-scene-07-rust-hospital-entry",
    mood: "恐惧、抗拒、必须下去",
    mechanic: "医院地图、应急灯、电闸目标",
    gameplay: "玩家需要恢复急救电闸，照亮通往地下的路径。每次开闸都会提升怪物警觉。",
    description:
      "医院不是医疗空间，而是事故报告里被消毒水掩盖的真相。病床倒挂、输液管像血管垂落，墙上箭头指向地下停尸房，逼迫沈迴走向那个他一直绕开的地点。",
    panels: [
      {
        shot: "医院外观",
        imageDirection: "锈红色废弃医院，破窗、急诊残字、雾从门缝向外翻。",
        narration: "消毒水味还没散，像有人刚刚试图把真相擦掉。",
      },
      {
        shot: "走廊主观镜头",
        imageDirection: "手电光扫过地下停尸房指示牌，推车倾倒，血迹干涸。",
        dialogue: "沈迴：我不该下去。但她在下面。",
      },
    ],
    objectives: ["找到三处电闸", "避开走廊巡逻", "打开地下通道"],
    artPrompt: `${cinematicStyle} Scene: abandoned rust-colored hospital corridor, upside-down beds, dangling IV tubes, old emergency lights, flashlight beam pointing toward basement sign, oppressive medical horror, no readable text.`,
  },
  {
    id: "scene-08-listener-encounter",
    act: "第二幕",
    order: "08",
    kind: "main",
    title: "第一次遇见聆听者",
    subtitle: "停下来才算面对",
    location: "医院地下走廊",
    image: "/assets/monsters/monster-listener.png",
    assetSlug: "comic-scene-08-listener-encounter",
    mood: "窒息、克制、被听见",
    mechanic: "声音怪物、静止隐身、噪音教学",
    gameplay: "玩家必须完全松开移动键，等待聆听者经过。心跳和噪音条成为主要信息源。",
    description:
      "聆听者几乎没有视觉能力，它审判的不是你在哪里，而是你有没有停止为自己辩解。玩家本能会想逃跑，但系统第一次要求玩家用静止解决危险。",
    panels: [
      {
        shot: "黑暗呼吸",
        imageDirection: "几乎全黑，只有手电光边缘照到贴墙的无眼怪物和巨大耳廓。",
        narration: "它看不见你，但它听见你想逃。",
        interaction: "停止移动，噪音归零后怪物离开。",
      },
      {
        shot: "擦肩而过",
        imageDirection: "怪物从主角半米外经过，主角屏息，手电光被压到地面。",
        dialogue: "沈迴：它在听什么？听我的心跳，还是我说不出口的话？",
      },
    ],
    objectives: ["静止通过聆听者", "学习噪音惩罚", "进入档案室"],
    artPrompt: `${cinematicStyle} Scene: eyeless listener monster clinging to a hospital wall, oversized ears, flashlight grazing its wet silhouette, protagonist frozen in fear nearby, near-black composition, tense silence.`,
  },
  {
    id: "scene-09-rewritten-report",
    act: "第二幕",
    order: "09",
    kind: "main",
    title: "改写的事故报告",
    subtitle: "把选择改成抢救无效",
    location: "医院地下档案室",
    image: "/assets/scenes/scene-rust-hospital.png",
    assetSlug: "comic-scene-09-rewritten-report",
    mood: "愤怒、爆发、自我指控",
    mechanic: "证物对照、报告拼读、真相碎片",
    gameplay: "玩家把手写报告和正式报告拼在同一张桌上，找出被删改的字段。找到全部差异后触发闪回。",
    description:
      "档案室像一座纸做的坟墓。原始报告上保留了水位、伤者数量和沈迴的临场判断；正式报告把三个人改成一个，把选择改成天灾，把所有人都训练成遗忘。",
    panels: [
      {
        shot: "文件对照",
        imageDirection: "两份报告并排摊在潮湿地面，手写涂改和整洁打印形成强烈对比。",
        narration: "系统替你写好了无罪，但雾拒绝签字。",
        interaction: "点选报告差异：伤亡人数、责任方、医生备注。",
      },
      {
        shot: "签字闪回",
        imageDirection: "办公室里的西装男人推来报告，沈迴的手握笔停在签名处。",
        dialogue: "顾承：签字，一切就结束了。",
      },
    ],
    objectives: ["比对两份报告", "收集改写证据", "解锁顾承追猎者线索"],
    artPrompt: `${cinematicStyle} Scene: flooded archive room in abandoned hospital, two accident reports on wet floor, flashlight and shaking hands, filing cabinets fallen, paper everywhere, moral dread, no readable text.`,
  },
  {
    id: "scene-10-old-wu-companion",
    act: "第二幕",
    order: "10",
    kind: "main",
    title: "遇见老吴",
    subtitle: "没有进去的人也被雾留下",
    location: "地下室避难角",
    image: "/assets/characters/character-rescued-survivor.png",
    assetSlug: "comic-scene-10-old-wu-companion",
    mood: "沉默、同罪、谨慎结盟",
    mechanic: "同行者选择、信任值、护送",
    gameplay: "玩家可以选择带上老吴或独自离开。带上后获得线索提示，但移动噪音与护送风险上升。",
    description:
      "老吴不是需要拯救的普通 NPC，而是另一种罪责。他站在事故现场门外听见过呼救，却没有进去。玩家救下他，其实是在回答旁观者是否也值得被宽恕。",
    panels: [
      {
        shot: "避难角远景",
        imageDirection: "旧消防外套老人蹲在雾里，手攥一串生锈钥匙。",
        dialogue: "老吴：我在现场。我听到了，但我没进去。",
      },
      {
        shot: "选择界面",
        imageDirection: "沈迴伸手，老人抬头，背后走廊灯一盏盏熄灭。",
        interaction: "选择：带他走，或独自前进。",
      },
    ],
    objectives: ["决定是否救下老吴", "建立同行者信任", "进入肉墙地下道"],
    choices: [
      { label: "跟我来", consequence: "老吴成为同行者，后续可提示追猎者动向。", moralTag: "survivorsSaved" },
      { label: "我自己走", consequence: "降低护送压力，但牺牲结局路径受限。", moralTag: "survivorsAbandoned" },
    ],
    artPrompt: `${cinematicStyle} Scene: retired firefighter in old coat crouching in a ruined hospital basement, rusty keys in hand, protagonist offers help under weak flashlight, fog pooling around their feet, quiet guilt.`,
  },
  {
    id: "scene-11-flesh-tunnel-tracker",
    act: "第二幕",
    order: "11",
    kind: "main",
    title: "肉墙地下道 - 水纹追踪器",
    subtitle: "怪物也会留下路径",
    location: "肉墙地下道",
    image: "/assets/scenes/scene-flesh-tunnel.png",
    assetSlug: "comic-scene-11-flesh-tunnel-tracker",
    mood: "恶心、观察、理解路径",
    mechanic: "水纹追踪、怪物轨迹、狭道风险",
    gameplay: "玩家拾取水纹追踪器后能看到怪物过去几秒的路径。狭窄通道强化匍匐者速度。",
    description:
      "地下道像活物一样收缩，墙面脉动，血水把地面变成记忆的底片。水纹追踪器让玩家第一次不只看怪物位置，而是阅读怪物的过去。",
    panels: [
      {
        shot: "道具特写",
        imageDirection: "发光圆盘半浸在积水里，周围浮出蓝色虚线路径。",
        narration: "你不能改变它们走过哪里，但你能知道它们怎样走到这里。",
        interaction: "拾取水纹追踪器，观察怪物残影。",
      },
      {
        shot: "地下道纵深",
        imageDirection: "狭窄肉质墙面、低矮水道、远处红色轨迹突然转向。",
      },
    ],
    objectives: ["拾取追踪器", "利用轨迹绕开怪物", "搬运心脏保险丝"],
    artPrompt: `${cinematicStyle} Scene: organic fleshy underground tunnel with shallow reflective water, glowing circular ripple tracker device, blue ghost trails showing monster movement, claustrophobic body-horror texture, restrained gore.`,
  },
  {
    id: "scene-12-stalker-gu-cheng",
    act: "第二幕",
    order: "12",
    kind: "main",
    title: "追猎者 - 顾承的具象化",
    subtitle: "签字了吗",
    location: "肉墙地下道深处",
    image: "/assets/monsters/monster-stalker.png",
    assetSlug: "comic-scene-12-stalker-gu-cheng",
    mood: "追责、崩溃、被共犯感咬住",
    mechanic: "长追击、死咬、视线切断",
    gameplay: "追猎者丢失视线后仍会追踪一段时间。玩家要连续切断视线并拉开距离，而不是只躲进房间。",
    description:
      "顾承已经死了，但他的签字、掩盖和那句“你也是受害者”还在追。追猎者穿着破碎西装，走过的地方留下水迹，像一份永远不会干的报告。",
    panels: [
      {
        shot: "怪物显形",
        imageDirection: "高大西装怪物从雾里走出，面部扭曲但保留院长五官，脚下拖着水。",
        dialogue: "追猎者：沈医生，签字了吗？",
      },
      {
        shot: "手持追逐",
        imageDirection: "镜头剧烈晃动，走廊灯光拉成长线，怪物脚步始终在身后。",
        interaction: "连续转角、关门、熄灯，削弱追踪锁定。",
      },
    ],
    objectives: ["逃离追猎者", "切断视线三次", "找到林晨遗书"],
    artPrompt: `${cinematicStyle} Scene: tall stalker monster in torn formal suit, distorted elderly face, dragging water trails through fleshy tunnel fog, protagonist fleeing with flashlight, relentless pursuit, cinematic motion blur.`,
  },
  {
    id: "scene-13-lin-chen-letter",
    act: "第二幕",
    order: "13",
    kind: "main",
    title: "林晨的遗书",
    subtitle: "别人已经宽恕，自己还没有",
    location: "地下临时避难室",
    image: "/assets/scenes/scene-rust-hospital.png",
    assetSlug: "comic-scene-13-lin-chen-letter",
    mood: "悲痛、无法接受、情感核心",
    mechanic: "长文本证物、情绪停顿、理智恢复失败",
    gameplay: "玩家逐段阅读遗书，每读完一段会出现可互动记忆片段。读完后理智不恢复，提示创伤不是靠信息解决。",
    description:
      "遗书告诉沈迴：林晨不怪他，甚至理解那个不可能的选择。但这并没有立刻治愈他，反而让他的防线崩塌，因为他最不能接受的是自己竟然需要被原谅。",
    panels: [
      {
        shot: "防水袋特写",
        imageDirection: "折叠床、熄灭手提灯、防水袋里的信纸，纸边被水泡软。",
        narration: "宽恕已经存在，难的是接住它。",
      },
      {
        shot: "阅读崩溃",
        imageDirection: "沈迴坐在床边读信，老吴沉默站在背后，雾从门缝涌入。",
        dialogue: "沈迴：原谅自己？林晨，我做不到。",
      },
    ],
    objectives: ["读完遗书", "解锁林晨记忆", "进入第二幕下沉仪式"],
    artPrompt: `${cinematicStyle} Scene: small temporary shelter in underground hospital tunnel, waterproof bag with a handwritten letter on a folding bed, exhausted doctor reading and breaking down, old firefighter behind him, dim lantern, emotional horror.`,
  },
  {
    id: "scene-14-second-descent",
    act: "第二幕",
    order: "14",
    kind: "main",
    title: "第二幕结束 - 再次下沉",
    subtitle: "名字还不够，必须归还",
    location: "地下道召回印记",
    image: "/assets/ui/recall-sigil.png",
    assetSlug: "comic-scene-14-second-descent",
    mood: "抑郁、接受边缘、同行开始",
    mechanic: "同行者过场、灰烬系统解锁",
    gameplay: "老吴会停在印记边缘，玩家选择等待或独自踏入。下一层开始出现灰烬拾取与归还。",
    description:
      "第二次下沉不再是独自坠落。老吴站在印记旁承认自己还不够格，沈迴第一次对另一个人说“等我回来”。这句话把求生循环变成了承诺循环。",
    panels: [
      {
        shot: "印记边缘",
        imageDirection: "老吴站在暗处，沈迴站在发光印记内，两人中间隔着雾。",
        dialogue: "老吴：你先下去。我还不够格。",
      },
      {
        shot: "教堂预告",
        imageDirection: "下沉画面中闪过陶罐、模糊姓名和灰烬飞散。",
        narration: "你开始记起他们的名字，但名字还不够。",
      },
    ],
    objectives: ["确认下沉", "解锁灰烬归还", "进入灰烬教堂"],
    artPrompt: `${cinematicStyle} Scene: glowing recall sigil in a living underground tunnel, old firefighter waits at the edge while protagonist descends alone, ash particles and ceramic urn silhouettes appear in fog, somber gold light.`,
  },
  {
    id: "scene-15-ash-church-ritual",
    act: "第三幕",
    order: "15",
    kind: "main",
    title: "灰烬教堂 - 归还的仪式",
    subtitle: "死者不是事故，是名字",
    location: "灰烬教堂",
    image: "/assets/scenes/scene-ash-church.png",
    assetSlug: "comic-scene-15-ash-church-ritual",
    mood: "敬畏、悲伤、主动承担",
    mechanic: "灰烬拾取、仪式点、危险降低",
    gameplay: "玩家拾取带姓名的灰烬罐，并在祭坛印记处归还。归还会降低危险、恢复理智，但需要停留完成仪式。",
    description:
      "教堂是本作叙事玩法的核心：这里不奖励杀怪，而奖励停留、阅读和归还。数十个陶罐摆在祭坛上，每一个都代表事故报告里被抹平的人。",
    panels: [
      {
        shot: "教堂内景",
        imageDirection: "破碎彩绘玻璃、倾斜钟楼、中央祭坛上摆满小陶罐。",
        narration: "这里没有出口，只有选择。",
      },
      {
        shot: "姓名特写",
        imageDirection: "陶罐上刻着模糊姓名，手电照亮时灰烬像雪一样上浮。",
        dialogue: "沈迴：归还名字，但我连他们是谁都不知道。",
      },
    ],
    objectives: ["拾取第一个灰烬罐", "找到祭坛印记", "学习归还机制"],
    artPrompt: `${cinematicStyle} Scene: abandoned small church filled with ceramic ash urns on a stone altar, broken stained glass, ash falling like snow, protagonist with flashlight at doorway, sacred grief, muted gold and gray.`,
  },
  {
    id: "scene-16-first-ash",
    act: "第三幕",
    order: "16",
    kind: "main",
    title: "第一次拾取灰烬",
    subtitle: "王建国的声音从罐中回响",
    location: "灰烬教堂祭坛",
    image: "/assets/scenes/scene-ash-church.png",
    assetSlug: "comic-scene-16-first-ash",
    mood: "震动、羞愧、开始道歉",
    mechanic: "灰烬记忆闪回、临终托付",
    gameplay: "触碰灰烬后进入短暂记忆格，玩家要在失真画面中找到死者的名字和托付对象。",
    description:
      "灰烬不是收藏品，而是一个带重量的名字。王建国的记忆让沈迴重新听见那句“我女儿还在等我”，它把小雨线索和事故核心第一次连在一起。",
    panels: [
      {
        shot: "触碰瞬间",
        imageDirection: "沈迴手碰到陶罐，画面闪成积水地下室，一个中年男人抓着管道呼救。",
        dialogue: "王建国：救救我，我女儿还在等我。",
      },
      {
        shot: "现实跪倒",
        imageDirection: "沈迴抱着陶罐跪在祭坛前，灰烬光点绕着他缓慢旋转。",
        dialogue: "沈迴：我听到了。我听到了他的声音。",
      },
    ],
    objectives: ["识别王建国", "记录小雨线索", "决定是否归还"],
    choices: [
      { label: "归还王建国", consequence: "小雨可被救下，理智恢复。", moralTag: "ashesReturned" },
      { label: "暂时带走", consequence: "保留选择，但危险持续上升。", moralTag: "ashesCarried" },
    ],
    artPrompt: `${cinematicStyle} Scene: ceramic ash urn glowing in protagonist's hands, memory vision of a middle-aged man trapped in rising flood water, church altar and basement memory double exposure, tragic and intimate.`,
  },
  {
    id: "scene-17-xiaoyu-companion",
    act: "第三幕",
    order: "17",
    kind: "main",
    title: "遇见小雨",
    subtitle: "她等的不是出口，是父亲",
    location: "灰烬教堂角落",
    image: "/assets/characters/character-rescued-survivor.png",
    assetSlug: "comic-scene-17-xiaoyu-companion",
    mood: "温柔、哀伤、责任扩大",
    mechanic: "第二同行者、牵手提示、儿童视角线索",
    gameplay: "小雨不会主动攻击或解谜，但会指向与父亲有关的灰烬和学校物件。护送她会改变后续结局。",
    description:
      "小雨是被事故间接吞没的人。她不知道父亲死亡的真相，只知道自己一直在等。她的存在让沈迴面对受害者家属，而不只是死者名单。",
    panels: [
      {
        shot: "长椅后的小身影",
        imageDirection: "脏校服女孩躲在教堂长椅后，赤脚，手里攥褪色全家福。",
        dialogue: "沈迴：你叫什么名字？",
      },
      {
        shot: "全家福特写",
        imageDirection: "照片上父亲名字与陶罐姓名呼应，女孩手指指向灰烬罐。",
        dialogue: "沈迴：你一直在等他。",
      },
    ],
    objectives: ["与小雨互动", "确认王建国关系", "选择是否同行"],
    choices: [
      { label: "带她找爸爸", consequence: "小雨加入同行者，开启学校支线。", moralTag: "survivorsSaved" },
      { label: "我帮不了你", consequence: "小雨留在教堂，牺牲结局无法达成。", moralTag: "survivorsAbandoned" },
    ],
    artPrompt: `${cinematicStyle} Scene: quiet young girl in dirty school uniform hiding behind broken church pews, holding faded family photo, ash urns and fog around her, protagonist kneels gently with flashlight, sorrowful not exploitative.`,
  },
  {
    id: "scene-18-return-first-ash",
    act: "第三幕",
    order: "18",
    kind: "main",
    title: "归还仪式 - 第一个灰烬",
    subtitle: "不是复活，是让存在被承认",
    location: "灰烬教堂祭坛印记",
    image: "/assets/scenes/scene-ash-church.png",
    assetSlug: "comic-scene-18-return-first-ash",
    mood: "哀悼、释放、第一次主动道歉",
    mechanic: "长按归还、危险下降、同行者情绪变化",
    gameplay: "玩家长按 G 完成归还。仪式期间不能移动，怪物会靠近，但小雨的哭声会短暂驱散幻影。",
    description:
      "归还王建国的名字不是救活他，而是让他终于抵达小雨面前。灰烬化作温暗金色轮廓，父女只获得几秒钟相见，这几秒钟就是仪式的全部意义。",
    panels: [
      {
        shot: "仪式光点",
        imageDirection: "陶罐裂开，灰烬变成金色光点，父亲轮廓在祭坛前显形。",
        narration: "记住不是惩罚，它也可以是抵达。",
      },
      {
        shot: "小雨哭泣",
        imageDirection: "女孩跪在光里第一次哭出声，沈迴抱住她。",
        dialogue: "沈迴：对不起，让你等了这么久。",
      },
    ],
    objectives: ["完成王建国归还", "降低危险", "开启沉没学校方向"],
    artPrompt: `${cinematicStyle} Scene: ash return ritual in ruined church, golden particles form a gentle father silhouette before a crying little girl, protagonist kneels nearby, sacred grief, no religious icon dominance, original sigil light.`,
  },
  {
    id: "scene-19-wall-of-names",
    act: "第三幕",
    order: "19",
    kind: "main",
    title: "教堂深处 - 更多的灰烬",
    subtitle: "活着的人也在名单上",
    location: "灰烬教堂名单墙",
    image: "/assets/scenes/scene-ash-church.png",
    assetSlug: "comic-scene-19-wall-of-names",
    mood: "震惊、承担、幸存者罪责显形",
    mechanic: "名单墙、连续归还、收集路线扩展",
    gameplay: "玩家在名单墙上点亮死者姓名，部分姓名会在地图上生成灰烬目标。沈迴自己的名字被划掉，触发理智波动。",
    description:
      "名单墙把事故从单一悲剧扩展成系统性遗忘。沈迴发现自己的名字也在上面，只是被划掉，这说明雾不只记录死者，也记录那些被困在活着里的遇难者。",
    panels: [
      {
        shot: "名单墙",
        imageDirection: "巨大名单挂在教堂后墙，许多名字模糊，少数被手电照亮。",
        dialogue: "老吴：也许我们都是遇难者，只是有些人还活着。",
      },
      {
        shot: "划掉的姓名",
        imageDirection: "沈迴在名单上看到自己的名字被划掉，镜头推近他的眼睛。",
      },
    ],
    objectives: ["点亮名单墙", "生成剩余灰烬目标", "拾取小雨失踪报告"],
    artPrompt: `${cinematicStyle} Scene: enormous victim name list wall inside ruined ash church, protagonist and old firefighter looking up, many names blurred by damp and ash, one crossed-out line illuminated by flashlight, solemn wide shot.`,
  },
  {
    id: "scene-20-sunken-school-entry",
    act: "第三幕",
    order: "20",
    kind: "main",
    title: "沉没学校",
    subtitle: "她终于开始说话",
    location: "沉没小学",
    image: "/assets/scenes/scene-sunken-school.png",
    assetSlug: "comic-scene-20-sunken-school-entry",
    mood: "童年创伤、迟来的哀悼",
    mechanic: "水位、漂浮课桌、儿童线索",
    gameplay: "玩家引导小雨穿过半淹学校，寻找作业本和日记。水位会改变路径，残暴者堵住正面通道。",
    description:
      "学校把小雨从等待状态带回失踪前的生活。课桌漂在灰白水面，钢琴错音不断重复。小雨第一次开口，说明她开始从创伤麻木中醒来。",
    panels: [
      {
        shot: "操场远景",
        imageDirection: "半淹没小学，课桌从教室窗口漂出，操场积水倒映雾光。",
        dialogue: "小雨：这是我的学校吗？",
      },
      {
        shot: "儿童画走廊",
        imageDirection: "墙上儿童画描绘父亲上班、母亲做饭，角落写着小雨名字。",
      },
    ],
    objectives: ["护送小雨进入学校", "找回作业本", "避开水位变化"],
    artPrompt: `${cinematicStyle} Scene: abandoned elementary school half submerged in pale water, floating desks, children's drawings on walls, little girl and protagonist reflected in flooded hallway, melancholy dawn-gray palette.`,
  },
  {
    id: "scene-21-brute-school",
    act: "第三幕",
    order: "21",
    kind: "main",
    title: "残暴者遭遇战",
    subtitle: "正面打不过否认",
    location: "沉没学校走廊",
    image: "/assets/monsters/monster-brute.png",
    assetSlug: "comic-scene-21-brute-school",
    mood: "压迫、策略、绕行",
    mechanic: "正面无效、背后击退、环境绕行",
    gameplay: "残暴者正面不可击退，玩家必须利用课桌、教室和十字架绕到背后。失败会被逼回水位更高区域。",
    description:
      "残暴者代表否认本身。它挡在走廊尽头反复低语“不是我的错”。玩家不能正面战胜它，必须承认有些心理防御无法被硬打碎，只能绕过、看见它的背面。",
    panels: [
      {
        shot: "走廊堵截",
        imageDirection: "巨大沉重怪物堵住半淹走廊，脸上是扭曲的拒绝表情。",
        dialogue: "老吴：它在拒绝。正面打不过。",
      },
      {
        shot: "背后破防",
        imageDirection: "主角绕到怪物背后，手电照出它脸上的泪痕和裂缝。",
        interaction: "从背后挥击，使残暴者失衡跪倒。",
      },
    ],
    objectives: ["绕到残暴者背后", "打开教室路径", "保护小雨不被分隔"],
    artPrompt: `${cinematicStyle} Scene: massive brute monster blocks a flooded school hallway, heavy armored body, twisted denial mask, protagonist sneaks behind desks with flashlight, strategic horror, water reflections.`,
  },
  {
    id: "scene-22-xiaoyu-diary",
    act: "第三幕",
    order: "22",
    kind: "main",
    title: "小雨的秘密",
    subtitle: "她不是被抛弃，只是没有人告诉她",
    location: "小雨的教室",
    image: "/assets/scenes/scene-sunken-school.png",
    assetSlug: "comic-scene-22-xiaoyu-diary",
    mood: "释放、哭泣、哀悼完成",
    mechanic: "日记证物、亲子托付、同行者安定",
    gameplay: "玩家打开课桌抽屉，逐页恢复日记。最后一页的水渍会生成通向海岸的光线。",
    description:
      "日记揭示小雨失踪不是悬疑谜题，而是一个孩子误以为父亲不要她，于是独自去找答案。沈迴必须亲口告诉她父亲不会回来，但父亲一直爱她。",
    panels: [
      {
        shot: "课桌抽屉",
        imageDirection: "刻着小雨名字的课桌，抽屉里有泡胀日记本。",
        narration: "真相有时残酷，但它比等待仁慈。",
      },
      {
        shot: "告知真相",
        imageDirection: "沈迴抱住哭泣的小雨，教室水面安静，远处钢琴错音停止。",
        dialogue: "沈迴：他不会回来了。但他一直爱着你。",
      },
    ],
    objectives: ["读取日记", "完成小雨哀悼", "显影海岸门"],
    artPrompt: `${cinematicStyle} Scene: flooded classroom, soaked diary in a carved desk, little girl crying while protagonist comforts her, piano silhouette in background, pale water and warm flashlight, tender psychological horror.`,
  },
  {
    id: "scene-23-third-act-promise",
    act: "第三幕",
    order: "23",
    kind: "main",
    title: "教堂的承诺",
    subtitle: "我欠他们的",
    location: "灰烬教堂回返",
    image: "/assets/scenes/scene-ash-church.png",
    assetSlug: "comic-scene-23-third-act-promise",
    mood: "接受、承诺、从赎罪转为责任",
    mechanic: "批量归还、伙伴协助、章节汇合",
    gameplay: "已救下的同行者会缩短归还仪式时间。玩家可选择继续归还更多灰烬或进入海岸。",
    description:
      "第三幕的高潮不是战斗，而是沈迴终于改变问题：不再问自己是否做错，而是问现在还能做什么。老吴和小雨不再只是被护送者，他们成为仪式的一部分。",
    panels: [
      {
        shot: "三人剪影",
        imageDirection: "沈迴、老吴、小雨站在温暗金光中，面前是剩余灰烬罐。",
        dialogue: "沈迴：我欠他们的。",
      },
      {
        shot: "名字清晰",
        imageDirection: "名单墙上的模糊名字逐渐变清，灰烬像翻页一样落下。",
        narration: "你归还了存在，但真相还在更深处。",
      },
    ],
    objectives: ["归还可选灰烬", "巩固同行者信任", "进入破晓海岸"],
    choices: [
      { label: "继续归还", consequence: "提高赎罪和牺牲结局权重。", moralTag: "ashesReturned" },
      { label: "先去海岸", consequence: "推进主线，未归还名字会影响结局。", moralTag: "truthFocused" },
    ],
    artPrompt: `${cinematicStyle} Scene: three survivors in ruined ash church surrounded by warm gold ash light, many ceramic urns, victim names on wall becoming clear, solemn group silhouette, hopeful but sad.`,
  },
  {
    id: "scene-24-dawn-coast",
    act: "第四幕",
    order: "24",
    kind: "main",
    title: "破晓海岸",
    subtitle: "雾不是问题，逃避才是",
    location: "破晓海岸",
    image: "/assets/scenes/scene-dawn-coast.png",
    assetSlug: "comic-scene-24-dawn-coast",
    mood: "开阔、清醒、准备直面",
    mechanic: "海浪声、低威胁、光线引导",
    gameplay: "场景从生存压力转向叙事探索。玩家沿退潮痕迹寻找漂流瓶、车灯碎片和病历夹。",
    description:
      "破晓海岸第一次给玩家真正的空间和呼吸。天边出现不是手电的光，海浪声清晰而真实。沈迴意识到他不再等待雾散，而是准备看清雾后面的东西。",
    panels: [
      {
        shot: "宽银幕海岸",
        imageDirection: "三人并排站在废弃海滩，远处晨曦穿过薄雾。",
        dialogue: "沈迴：雾从来不是问题。问题是我们一直在逃避看清它后面的东西。",
      },
      {
        shot: "退潮证物",
        imageDirection: "沙滩露出车灯碎片、病历夹和旧街牌，潮水像时间一样退去。",
      },
    ],
    objectives: ["搜索退潮证物", "找到漂流瓶", "准备追猎者对峙"],
    artPrompt: `${cinematicStyle} Scene: abandoned foggy beach at dawn, three figures standing side by side, tide reveals car light shards and medical folder in wet sand, first warm sunlight through gray fog, contemplative wide shot.`,
  },
  {
    id: "scene-25-message-in-bottle",
    act: "第四幕",
    order: "25",
    kind: "main",
    title: "海滩上的漂流瓶",
    subtitle: "未来的自己早已留下答案",
    location: "破晓海岸沙滩",
    image: "/assets/scenes/scene-dawn-coast.png",
    assetSlug: "comic-scene-25-message-in-bottle",
    mood: "自我对话、理智与情感冲突",
    mechanic: "信件阅读、过去自我闪回",
    gameplay: "玩家逐段展开潮湿信纸。每段后会出现一个可旋转的记忆瓶，拼齐后获得最终真相钥匙。",
    description:
      "漂流瓶里的信是事故后理性的沈迴写给未来的自己。它明白选择可能是正确的，也明白正确不等于不痛。这个场景把核心矛盾从外部罪责转向幸存者愧疚。",
    panels: [
      {
        shot: "玻璃瓶特写",
        imageDirection: "潮湿沙滩上的玻璃瓶，瓶内信纸仍然清晰，晨光照出水珠。",
        narration: "你不是在为做错的事赎罪，你是在为活着赎罪。",
      },
      {
        shot: "写信闪回",
        imageDirection: "2019 年积水地下室，年轻沈迴坐在担架旁颤抖写信。",
        dialogue: "沈迴：也许有一天，我能相信自己说的话。",
      },
    ],
    objectives: ["读取未来信", "拼合记忆瓶", "解锁自我宽恕主题"],
    artPrompt: `${cinematicStyle} Scene: glass bottle with a damp letter on dawn beach sand, exhausted doctor opens it with trembling hands, subtle overlay of flooded basement memory, gentle tragic light, no readable text.`,
  },
  {
    id: "scene-26-final-stalker-confrontation",
    act: "第四幕",
    order: "26",
    kind: "main",
    title: "追猎者的最终对峙",
    subtitle: "我不是来追你，是来面对你",
    location: "海滩尽头",
    image: "/assets/monsters/monster-stalker.png",
    assetSlug: "comic-scene-26-final-stalker-confrontation",
    mood: "直面、忏悔、宽恕前的沉默",
    mechanic: "非战斗对峙、距离保持、对白选择",
    gameplay: "玩家不能攻击追猎者，只能保持站定并选择回应。后退会延长对峙，站定会让顾承恢复清晰声音。",
    description:
      "追猎者这次不再奔跑，它疲惫地走来，像终于承认自己也是被雾追赶的人。顾承的忏悔无法改变过去，却把沈迴从等待别人道歉的阶段推进到自主选择。",
    panels: [
      {
        shot: "雾中来者",
        imageDirection: "西装怪物从海雾尽头走来，脚步沉重，眼中第一次有悲伤。",
        dialogue: "追猎者：沈医生。",
      },
      {
        shot: "面对面",
        imageDirection: "沈迴站定，没有举起武器，晨曦从两人之间穿过。",
        dialogue: "沈迴：我不是来追你。我来面对你。",
      },
    ],
    objectives: ["保持站定", "听完顾承忏悔", "进入宽恕选择"],
    artPrompt: `${cinematicStyle} Scene: final beach confrontation at dawn, distorted old director figure in torn suit faces protagonist calmly, fog and sea behind them, no combat pose, remorse and tension, cinematic profile composition.`,
  },
  {
    id: "scene-27-stalker-ash-choice",
    act: "第四幕",
    order: "27",
    kind: "branch",
    title: "追猎者的灰烬",
    subtitle: "归还名字不等于抹去罪责",
    location: "海岸仪式点",
    image: "/assets/scenes/scene-dawn-coast.png",
    assetSlug: "comic-scene-27-stalker-ash-choice",
    mood: "艰难、边界、选择宽恕或不宽恕",
    mechanic: "核心道德抉择、顾承灰烬、结局权重",
    gameplay: "玩家选择接过或拒绝顾承的灰烬罐。两者都能推进剧情，但会影响赎罪、真相和否认结局。",
    description:
      "顾承递出的不是免责书，而是他的名字。沈迴可以归还，也可以拒绝。系统不把宽恕做成标准答案，因为不原谅也可以是诚实的进步，只要玩家不再逃避。",
    panels: [
      {
        shot: "灰烬递出",
        imageDirection: "追猎者伸出手，掌心是一只暗淡发光的灰烬罐。",
        dialogue: "顾承：这是我的名字。我知道我不值得被归还。",
      },
      {
        shot: "分支选择",
        imageDirection: "沈迴的手悬在灰烬罐前，海风吹散雾，晨光未完全落下。",
        interaction: "选择接过或拒绝。",
      },
    ],
    objectives: ["决定是否接过顾承灰烬", "记录宽恕状态", "前往晨曦病房"],
    choices: [
      { label: "接过灰烬罐", consequence: "不是原谅罪责，而是不让仇恨继续追赶。", moralTag: "forgiveGuCheng" },
      { label: "拒绝接过", consequence: "承认现在无法原谅，追猎者不再追赶但灰烬留在海滩。", moralTag: "refuseForgiveness" },
    ],
    artPrompt: `${cinematicStyle} Scene: remorseful stalker figure offers a dim ash urn to protagonist on foggy dawn beach, close-up of two hands and urn, sea wind, moral ambiguity, muted gold and gray light.`,
  },
  {
    id: "scene-28-dawn-ward-entrance",
    act: "第四幕",
    order: "28",
    kind: "main",
    title: "晨曦病房的入口",
    subtitle: "一切开始，也一切结束",
    location: "疗养院外部",
    image: "/assets/scenes/scene-dawn-ward.png",
    assetSlug: "comic-scene-28-dawn-ward-entrance",
    mood: "临界、安静、无怪物的恐惧",
    mechanic: "安全区、伙伴停留、最终单人进入",
    gameplay: "玩家抵达一扇敞开的门。老吴和小雨会停下，玩家可与他们告别，获得不同结局标记。",
    description:
      "晨曦病房没有怪物，这反而让它更恐怖。老吴无法进入，因为他的罪责是没有进去；小雨不需要进入，因为她已经找到父亲。沈迴必须独自走完最后一段。",
    panels: [
      {
        shot: "病房外观",
        imageDirection: "比之前更干净明亮的废弃建筑，窗户透出暖黄色光，门敞开。",
        dialogue: "沈迴：也是一切结束的地方。",
      },
      {
        shot: "门口告别",
        imageDirection: "老吴坐在长椅边，小雨身影半透明，沈迴独自走进走廊。",
        dialogue: "老吴：你会回来吗？ 沈迴：我会带着真相回来。",
      },
    ],
    objectives: ["与同行者告别", "记录救援状态", "独自进入病房"],
    artPrompt: `${cinematicStyle} Scene: quiet dawn rehabilitation ward entrance, warm yellow window light, old firefighter and little girl remain at doorway while protagonist walks inside alone, fog thinning, emotional threshold.`,
  },
  {
    id: "scene-29-dawn-ward-corridor",
    act: "第四幕",
    order: "29",
    kind: "main",
    title: "进入晨曦病房",
    subtitle: "没有脚步声，只剩钢琴",
    location: "晨曦病房走廊",
    image: "/assets/scenes/scene-dawn-ward.png",
    assetSlug: "comic-scene-29-dawn-ward-corridor",
    mood: "平静、空白、临终前的安宁",
    mechanic: "无战斗探索、环境叙事、BGM 转调",
    gameplay: "玩家只能步行，不能冲刺和攻击。墙上照片、病历夹和旧标识拼出疗养院事故前状态。",
    description:
      "走廊干净得不真实，像雾临时搭出的赦免空间。所有恐怖音效消失，轻柔钢琴取代心跳。玩家被迫放慢，因为最终真相不是追出来的，是走进去的。",
    panels: [
      {
        shot: "干净走廊",
        imageDirection: "白色康复中心走廊，暖光，墙上旧照片，地面没有水迹。",
        narration: "危险消失后，留下的空白才最难承受。",
      },
      {
        shot: "照片墙",
        imageDirection: "事故前疗养院合影，沈迴在照片边缘模糊出现。",
        interaction: "查看照片，解锁事故前时间线。",
      },
    ],
    objectives: ["查看照片墙", "放慢移动", "抵达急救室门前"],
    artPrompt: `${cinematicStyle} Scene: unnaturally clean dawn ward corridor in abandoned rehabilitation center, warm window light, old photographs on wall, protagonist walking alone, calm unsettling atmosphere, painterly game illustration.`,
  },
  {
    id: "scene-30-truth-room-door",
    act: "第四幕",
    order: "30",
    kind: "main",
    title: "真相之室门前",
    subtitle: "门把在颤抖",
    location: "急救室门前",
    image: "/assets/scenes/scene-dawn-ward.png",
    assetSlug: "comic-scene-30-truth-room-door",
    mood: "临界、恐惧、最后抗拒",
    mechanic: "长按开门、白光过场、不可回头",
    gameplay: "玩家长按门把，期间会听到过去四个方向的呼救声。松手会退回走廊，按满进入记忆重历。",
    description:
      "门后不是新地点，而是同一个晚上的重新经历。镜头集中在门把和沈迴的手，玩家需要主动按住，把自己送回最不愿记起的瞬间。",
    panels: [
      {
        shot: "门把特写",
        imageDirection: "急救室门把在白光边缘颤抖，沈迴的手覆盖上去。",
        dialogue: "沈迴：门后面，是我亲眼看到但不敢记起的真相。",
        interaction: "长按开门，呼救声逐渐变清。",
      },
      {
        shot: "白光涌出",
        imageDirection: "门缝放出刺眼白光，走廊被吞没。",
      },
    ],
    objectives: ["长按开门", "接受不可回头提示", "进入 2019 年事故夜"],
    artPrompt: `${cinematicStyle} Scene: close-up of trembling hand on emergency room door handle, intense white light leaking from door crack, warm dawn ward corridor dissolving into memory, suspenseful minimal composition.`,
  },
  {
    id: "scene-31-emergency-room-night",
    act: "第四幕",
    order: "31",
    kind: "main",
    title: "急救室 - 那个晚上",
    subtitle: "重新成为当时的自己",
    location: "2019 年地下蓄水层",
    image: "/assets/scenes/scene-rust-hospital.png",
    assetSlug: "comic-scene-31-emergency-room-night",
    mood: "重历、创伤、不可逃避",
    mechanic: "记忆回放、年轻身体、限制行动",
    gameplay: "玩家进入过去场景，UI 消失，只剩水位、呼救方向和林晨生命状态。目标不是赢，而是理解限制。",
    description:
      "白光褪去后，沈迴不再是观察者。他穿着急救服，手也年轻了几岁。玩家知道未来，但身体回到过去，游戏用控制权与限制制造创伤重历。",
    panels: [
      {
        shot: "白光褪去",
        imageDirection: "积水地下蓄水层，应急灯闪烁，水到小腿，远处管道轰鸣。",
        narration: "你回来了，不是旁观，而是重新经历。",
      },
      {
        shot: "低头看手",
        imageDirection: "年轻沈迴的急救手套沾水和血，手电换成头灯和应急灯。",
      },
    ],
    objectives: ["适应过去身体", "定位林晨", "听见远处呼救"],
    artPrompt: `${cinematicStyle} Scene: flooded underground reservoir on rainy accident night, emergency lights flickering, young emergency doctor looks at gloved hands in shin-deep water, pipes and rising water, traumatic realism, no gore focus.`,
  },
  {
    id: "scene-32-replay-choice-linchen",
    act: "第四幕",
    order: "32",
    kind: "main",
    title: "重历抉择 - 林晨",
    subtitle: "你只能救一个",
    location: "事故现场担架旁",
    image: "/assets/characters/character-rescued-survivor.png",
    assetSlug: "comic-scene-32-replay-choice-linchen",
    mood: "撕裂、无解、医生的诅咒",
    mechanic: "无法改变的选择、生命状态条",
    gameplay: "玩家可以尝试离开林晨去救远处两人，但每次水位和林晨状态都会让行动失败。系统明确提示物理限制。",
    description:
      "这是最残酷也最诚实的互动：让玩家亲手尝试救所有人，然后发现结果只会更坏。选择不是道德题，而是水位、伤势和时间共同构成的物理极限。",
    panels: [
      {
        shot: "林晨担架",
        imageDirection: "林晨躺在临时担架上，清醒但虚弱，水在担架腿边上涨。",
        dialogue: "林晨：你救不了所有人的。这不是你的错。",
      },
      {
        shot: "分叉呼救",
        imageDirection: "镜头一边是林晨，一边是黑暗深处两束求救手电反光。",
        interaction: "尝试走向呼救声，会被上涨水位逼回。",
      },
    ],
    objectives: ["尝试救援远处两人", "理解林晨可救状态", "接受无解限制"],
    artPrompt: `${cinematicStyle} Scene: emergency doctor kneels beside injured nurse on temporary stretcher in flooded basement, distant rescue cries implied by lights in darkness, rising water, impossible choice, emotional cinematic framing.`,
  },
  {
    id: "scene-33-truth-of-cries",
    act: "第四幕",
    order: "33",
    kind: "main",
    title: "呼救声的真相",
    subtitle: "不是放弃，是过不去",
    location: "更深的蓄水层",
    image: "/assets/scenes/scene-rust-hospital.png",
    assetSlug: "comic-scene-33-truth-of-cries",
    mood: "无力、目睹、幸存者愧疚核心",
    mechanic: "水位阻挡、风险模拟、三人皆亡预警",
    gameplay: "系统显示如果继续前进，林晨会失血、沈迴会被水流困住，远处两人仍无法触及。",
    description:
      "沈迴真正逃避的不是自己做错，而是自己亲眼看见有人求救却无能为力。玩家向前走，水位上涨到胸口，应急灯进水短路，游戏把“过不去”做成可触摸的墙。",
    panels: [
      {
        shot: "远处两人",
        imageDirection: "王建国抓着管道，陈志远被杂物缠住，水到胸口，距离被黑水拉长。",
        dialogue: "王建国：医生，这里还有人在这里！",
      },
      {
        shot: "水位阻断",
        imageDirection: "沈迴向前一步，水猛然涨到胸口，远处灯光熄灭。",
        narration: "如果你过去，三个人都会死。",
      },
    ],
    objectives: ["接近呼救方向", "触发风险模拟", "退回林晨身边"],
    artPrompt: `${cinematicStyle} Scene: flooded basement rescue, two distant figures trapped in chest-high dark water, emergency doctor blocked by dangerous current and rising water, emergency lights shorting out, unbearable helplessness.`,
  },
  {
    id: "scene-34-last-words",
    act: "第四幕",
    order: "34",
    kind: "main",
    title: "最后的对话",
    subtitle: "带着他们的话活下去",
    location: "事故现场水面",
    image: "/assets/scenes/scene-rust-hospital.png",
    assetSlug: "comic-scene-34-last-words",
    mood: "崩溃、托付、责任诞生",
    mechanic: "临终托付记录、灰烬生成",
    gameplay: "玩家必须把两人的最后托付按顺序记住。记错不会失败，但会让后续归还仪式更长。",
    description:
      "王建国和陈志远消失前留下的不是控诉，而是托付。沈迴背负的从此不是罪名，而是声音：告诉女儿，告诉未婚妻，告诉世界他们存在过。",
    panels: [
      {
        shot: "水面吞没",
        imageDirection: "两个身影逐渐被水和黑暗吞没，应急灯光在水面碎裂。",
        dialogue: "王建国：告诉小雨，爸爸爱她。不是她的错。",
      },
      {
        shot: "跪水崩溃",
        imageDirection: "沈迴跪在水中，双手攥紧，林晨在担架上看着他。",
        dialogue: "林晨：现在，救我出去。带着他们的话活下去。",
      },
    ],
    objectives: ["记录王建国托付", "记录陈志远托付", "稳定林晨离开现场"],
    artPrompt: `${cinematicStyle} Scene: emergency doctor kneeling in flood water as distant trapped figures disappear beneath dark water, injured nurse on stretcher nearby, shattered emergency light reflections, grief and responsibility.`,
  },
  {
    id: "scene-35-realization",
    act: "第四幕",
    order: "35",
    kind: "main",
    title: "回到现实 - 顿悟",
    subtitle: "记得不是罪，是责任",
    location: "晨曦病房急救室",
    image: "/assets/scenes/scene-dawn-ward.png",
    assetSlug: "comic-scene-35-realization",
    mood: "顿悟、平静、责任重构",
    mechanic: "急救日志、三只灰烬罐、真相完成",
    gameplay: "玩家回到病房，拾取沈迴急救日志。三只灰烬罐出现在手中，开启最终仪式条件。",
    description:
      "真相把沈迴从“我做错了”改写成“我必须记得”。急救日志证明他从一开始就知道要记住所有人，只是后来被报告、沉默和愧疚埋住了。",
    panels: [
      {
        shot: "现实跪地",
        imageDirection: "沈迴跪在明亮急救室中央，泪流满面，手中出现三只灰烬罐。",
        narration: "这是责任，也是他们留给我的礼物。",
      },
      {
        shot: "急救日志",
        imageDirection: "旧急救日志最后一页摊开，旁边是手电和湿痕。",
        dialogue: "沈迴：我答应过要记住他们。现在，我做到了。",
      },
    ],
    objectives: ["拾取急救日志", "获得林晨和陈志远灰烬", "准备林晨告别"],
    artPrompt: `${cinematicStyle} Scene: bright dawn emergency room, protagonist kneels crying but calm, three small ash urns in his hands, old emergency log on floor, warm light and soft fog, realization not horror.`,
  },
  {
    id: "scene-36-linchen-farewell",
    act: "第四幕",
    order: "36",
    kind: "main",
    title: "林晨的告别",
    subtitle: "你终于接受了她的话",
    location: "急救室中央",
    image: "/assets/characters/hallucination-shadow.png",
    assetSlug: "comic-scene-36-linchen-farewell",
    mood: "温暖、告别、自我宽恕",
    mechanic: "完整幻象、最终问题预告",
    gameplay: "林晨完整显形。玩家不能跳过对白，需要选择是否接受“你从来没有错”这句话。",
    description:
      "林晨不再是雾状幻象，而是完整、温暖的人。第二幕沈迴读到宽恕时说“我做不到”，这里他终于能够回答“我明白了”。这是情感弧真正闭合的节点。",
    panels: [
      {
        shot: "光点汇聚",
        imageDirection: "急救室中央金色光点聚成人形，林晨完整显现。",
        dialogue: "林晨：你终于记起来了。",
      },
      {
        shot: "触碰脸颊",
        imageDirection: "林晨伸手轻触沈迴的脸，光线柔和，雾退到墙角。",
        dialogue: "林晨：因为你从来没有错。",
      },
    ],
    objectives: ["接受林晨告别", "确认自我宽恕状态", "开启最终三问"],
    choices: [
      { label: "我明白了", consequence: "开启赎罪、真相和牺牲结局路径。", moralTag: "selfForgiven" },
      { label: "我还做不到", consequence: "保留无尽或否认路径。", moralTag: "burdenContinues" },
    ],
    artPrompt: `${cinematicStyle} Scene: warm complete apparition of a nurse in dawn emergency room, gently touching exhausted doctor's face, golden particles, farewell and forgiveness, painterly emotional comic panel.`,
  },
  {
    id: "scene-37-final-three-questions",
    act: "第四幕",
    order: "37",
    kind: "branch",
    title: "最后的选择 - 出口的门",
    subtitle: "你会带着什么走出去",
    location: "发光的门前",
    image: "/assets/scenes/scene-dawn-ward.png",
    assetSlug: "comic-scene-37-final-three-questions",
    mood: "决定、清算、开放结局",
    mechanic: "三个最终问题、结局判定",
    gameplay: "玩家回答三问：说出真相或沉默；原谅自己或继续背负；永远记得或选择遗忘。",
    description:
      "最终选择不再考验玩家会不会搜证，而是考验玩家如何理解记得。说出真相未必温柔，沉默未必逃避；原谅自己不是忘记；记得也可能继续成为负担。",
    panels: [
      {
        shot: "门外晨曦",
        imageDirection: "急救室深处发光的门，外面是真实晨光和海风。",
        dialogue: "林晨：你的回答，决定你将带着什么走出这扇门。",
      },
      {
        shot: "三问界面",
        imageDirection: "三道光线投在地面，分别通向真相、自我、记忆的符号。",
        interaction: "依次选择三个回答，系统合并此前道德状态判定结局。",
      },
    ],
    objectives: ["回答是否说出真相", "回答是否原谅自己", "回答是否永远记得"],
    choices: [
      { label: "说出真相", consequence: "提高赎罪结局权重，也承担现实代价。", moralTag: "truthFaced" },
      { label: "保持沉默", consequence: "提高真相沉默结局权重，独自守护。", moralTag: "silenceChosen" },
      { label: "选择遗忘", consequence: "若承诺不足，可能滑向否认再沉。", moralTag: "forgetting" },
    ],
    artPrompt: `${cinematicStyle} Scene: glowing exit door inside dawn emergency room, three symbolic light paths on the floor, warm sunlight outside, apparition of nurse beside door, protagonist deciding, elegant interactive narrative composition.`,
  },
  {
    id: "scene-38-walk-through-door",
    act: "第四幕",
    order: "38",
    kind: "main",
    title: "走向门",
    subtitle: "雾将决定如何记得你",
    location: "出口门",
    image: "/assets/scenes/scene-dawn-ward.png",
    assetSlug: "comic-scene-38-walk-through-door",
    mood: "收束、纯白、等待判定",
    mechanic: "记忆蒙太奇、结局过场",
    gameplay: "玩家每走一步，前面章节的关键证物以漫画格闪回。推门后画面纯白，进入结局。",
    description:
      "沈迴走向门时，游戏把所有场景压缩成一条记忆走廊：急救记录单、林晨遗书、灰烬归还、小雨眼泪、那个夜晚。玩家的选择不是在最后一刻生成，而是一路被雾记下。",
    panels: [
      {
        shot: "证物蒙太奇",
        imageDirection: "四周浮现急救记录、遗书、陶罐、漂流瓶、急救日志的碎片。",
        narration: "你走到了尽头，也记起了一切。",
      },
      {
        shot: "推门纯白",
        imageDirection: "沈迴回头看林晨，林晨微笑挥手，他推门走入白光。",
      },
    ],
    objectives: ["回看关键证物", "推开出口", "进入五种结局之一"],
    artPrompt: `${cinematicStyle} Scene: protagonist walking toward blinding white exit door, floating memory fragments around him, nurse apparition waves goodbye, cinematic farewell, warm white light, no text.`,
  },
  {
    id: "ending-redemption",
    act: "最终章",
    order: "E1",
    kind: "ending",
    title: "赎罪·晨光",
    subtitle: "承担带来自由",
    location: "真实灰洄镇废墟外",
    image: "/assets/scenes/scene-dawn-coast.png",
    assetSlug: "comic-ending-redemption",
    mood: "希望、承担、公开真相",
    mechanic: "完美承诺结局、纪念馆尾声",
    gameplay: "归还所有灰烬、救下同行者、直面真相、原谅自己并说出真相时触发。",
    description:
      "雾散不是因为世界被修好，而是沈迴不再需要它来隐藏。三个月后，他公开事故真相，在纪念馆承担法律和舆论后果，让死者名字重新进入现实。",
    panels: [
      {
        shot: "废墟晨光",
        imageDirection: "真实晨曦照在疗养院废墟外，天空清澈，沈迴闭眼感受阳光。",
        narration: "记得不再是惩罚，而是承诺。",
      },
      {
        shot: "纪念馆",
        imageDirection: "社区小纪念馆墙上挂着遇难者照片，沈迴面对家属和记者。",
        dialogue: "沈迴：逃避了七年，现在我想堂堂正正地活着。",
      },
    ],
    objectives: ["公开真相", "承担现实后果", "完成救赎尾声"],
    artPrompt: `${cinematicStyle} Scene: real dawn outside ruined rehabilitation center with no fog, exhausted doctor in sunlight, later small memorial room with victim photos and families, hopeful restrained ending, original IP.`,
  },
  {
    id: "ending-truth",
    act: "最终章",
    order: "E2",
    kind: "ending",
    title: "真相·沉默",
    subtitle: "有些记得是无声的",
    location: "每年九月十五日的海岸",
    image: "/assets/scenes/scene-dawn-coast.png",
    assetSlug: "comic-ending-truth",
    mood: "孤独、慈悲、无声守护",
    mechanic: "沉默守护结局、年度仪式",
    gameplay: "找到全部证物并原谅自己，但最终选择保持沉默时触发。",
    description:
      "沈迴知道真相，也获得内心平静，但他选择不公开。他每年在海岸点四盏灯，把记住变成私人仪式。这不是逃避，而是一种带代价的慈悲。",
    panels: [
      {
        shot: "薄雾晨曦",
        imageDirection: "沈迴走出废墟，雾大部分散去但地平线仍有薄雾。",
        narration: "有些真相，只需要一个人记得就够了。",
      },
      {
        shot: "四盏小灯",
        imageDirection: "海岸沙滩上四盏小灯在晨风中摇曳，年老沈迴坐到天亮。",
      },
    ],
    objectives: ["守住证物", "每年点灯", "传递记忆责任"],
    artPrompt: `${cinematicStyle} Scene: lonely doctor at misty dawn beach lighting four small memorial lamps, years passing, quiet solemn ritual, thin fog on horizon, muted hopeful melancholy.`,
  },
  {
    id: "ending-sacrifice",
    act: "最终章",
    order: "E3",
    kind: "ending",
    title: "牺牲·留守",
    subtitle: "有人选择成为光",
    location: "雾中灰洄镇",
    image: "/assets/scenes/scene-endless-descent.png",
    assetSlug: "comic-ending-sacrifice",
    mood: "悲壮、利他、守夜",
    mechanic: "留下守护、未归还灰烬、指引者",
    gameplay: "救下同行者但仍有名字未归还，并选择留在雾中守护时触发。",
    description:
      "门就在眼前，但沈迴转身回雾里。他不是失败，而是选择把个人解脱让给还在等待的名字。最终他和同行者成为雾中的指引光。",
    panels: [
      {
        shot: "背对出口",
        imageDirection: "发光门在身后关闭，沈迴手握未归还灰烬罐走回雾中。",
        dialogue: "沈迴：这一次，我一个都不能少。",
      },
      {
        shot: "三盏微光",
        imageDirection: "雾中三个人影成为移动微光，远处新的迷失者举起手电。",
      },
    ],
    objectives: ["关闭个人出口", "继续归还名字", "成为雾中指引者"],
    artPrompt: `${cinematicStyle} Scene: protagonist turns away from glowing exit door into fog holding ash urns, old firefighter and little girl beside him, three small lights guide another lost figure, noble tragic ending.`,
  },
  {
    id: "ending-denial",
    act: "最终章",
    order: "E4",
    kind: "ending",
    title: "否认·再沉",
    subtitle: "逃避会走向更深",
    location: "更深一层的雾",
    image: "/assets/scenes/scene-endless-descent.png",
    assetSlug: "comic-ending-denial",
    mood: "堕落、轮回、失去自我",
    mechanic: "坏结局、逃避、怪物化",
    gameplay: "拒绝归还、抛弃同行者、选择遗忘或继续背负时触发。",
    description:
      "沈迴以为自己冲出了门，结果进入更深一层。未归还的名字、被抛弃的同行者和没说出口的真相把他拖回雾中，最终他成为新的游荡者。",
    panels: [
      {
        shot: "虚假阳光",
        imageDirection: "刺眼阳光迅速变灰，建筑和道路重新被雾吞没。",
        dialogue: "顾承的声音：逃避，是走不出去的。",
      },
      {
        shot: "怪物化远景",
        imageDirection: "雾中佝偻身影缓慢转向新的探索者，手电光照出它曾经是沈迴的轮廓。",
      },
    ],
    objectives: ["展示逃避后果", "循环回无尽下沉", "生成新的威胁"],
    artPrompt: `${cinematicStyle} Scene: false sunny exit collapses into deeper fog, protagonist transforms into a hunched wanderer silhouette, new explorer flashlight approaches, dark cyclical horror ending, no gore.`,
  },
  {
    id: "ending-endless",
    act: "最终章",
    order: "E5",
    kind: "ending",
    title: "无尽·下沉",
    subtitle: "旅程仍在继续",
    location: "雾中十字路口",
    image: "/assets/scenes/scene-endless-descent.png",
    assetSlug: "comic-ending-endless",
    mood: "悬而未决、徘徊、仍有机会",
    mechanic: "默认结局、roguelite 循环、继续游戏",
    gameplay: "承诺未完成且道德状态中性时触发。玩家可进入无尽模式，继续归还或改变下一次结局。",
    description:
      "沈迴没有得救，也没有堕落。他还在雾里走，手里仍有手电，也还记得一些名字。这个结局保留 roguelite 的循环本质：有些创伤需要反复面对。",
    panels: [
      {
        shot: "十字路口",
        imageDirection: "灰雾十字路口，没有门，只有多条向深处延伸的道路。",
        narration: "我还在这里，在记得和遗忘之间徘徊。",
      },
      {
        shot: "远处微光",
        imageDirection: "整座灰洄镇在雾中缓缓下沉又浮起，远处有其他探索者微光。",
      },
    ],
    objectives: ["进入无尽模式", "保留未完成承诺", "允许下一轮改变结局"],
    artPrompt: `${cinematicStyle} Scene: lone flashlight beam moving through endless foggy crossroads, folded harbor town sinking and rising in background, unresolved roguelite ending, melancholy and mysterious.`,
  },
];
